apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertman-freshservice
  labels:
    app: alertman-freshservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alertman-freshservice
  template:
    metadata:
      labels:
        app: alertman-freshservice
    spec:
      containers:
      - name: alertman-freshservice
        image: quay.io/phillipamend/alertman-freshservice
        imagePullPolicy: Always
        env:
        - name: FRESHSERVICE_API
          value: "https://youcompany.freshservice.com/api/v2/tickets"
        - name: REQUESTER_ID
          value: "REQUESTERID"
        - name: FRESHSERVICE_TOKEN
          value: "TOKEN"
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: alertman-freshservice-service
spec:
  selector:
    app: alertman-freshservice
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
